# Generated by Django 5.2.5 on 2025-08-16 19:25

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='subreddit_banners/'),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='subreddit_icons/'),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='joined_subreddits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', 'Subreddit names can only contain letters, numbers, and underscores.')]),
        ),
    ]
