# Generated by Django 5.2.5 on 2025-08-17 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0002_subreddit_banner_subreddit_icon_subreddit_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_subreddits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subreddit',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_subreddits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='subreddits.subreddit')),
            ],
        ),
    ]
