# Generated by Django 5.2.5 on 2025-08-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0003_alter_subreddit_creator_alter_subreddit_members_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rule',
            name='title',
            field=models.CharField(max_length=65),
        ),
    ]
