# Generated by Django 5.2.5 on 2025-08-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0004_alter_rule_description_alter_rule_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
