# Generated by Django 5.2.5 on 2025-08-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0005_alter_subreddit_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subreddit',
            old_name='creator',
            new_name='created_by',
        ),
    ]
